### ISSUE TITLE
Module cannot be initialized

### ISSUE THREAD

**Issue by SheGe** [agc93/Cake.BuildSystems.Module#17]
Hey,

I've found an issue where after addition of packages.config with just Cake.BuildSystems.Module to `./tools/Modules` is breaking the Cake build process.

*packages.config*

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake.BuildSystems.Module" version="0.3.0" />
</packages>
```

*Error with Diagnostic output:*

```console
Preparing to run build script...
Running build script...
Verifying assembly 'Cake.MyGet.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TeamCity.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TFBuild.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TravisCI.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.MyGet.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TeamCity.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TFBuild.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'Cake.TravisCI.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Registering module Cake.MyGet.Module.MyGetModule...
Registering module Cake.TeamCity.Module.TeamCityModule...
Registering module Cake.TFBuild.Module.TFBuildModule...
Registering module Cake.TravisCI.Module.TravisCIModule...
Registering module Cake.MyGet.Module.MyGetModule...
Registering module Cake.TeamCity.Module.TeamCityModule...
Registering module Cake.TFBuild.Module.TFBuildModule...
Registering module Cake.TravisCI.Module.TravisCIModule...
Error: System.TypeLoadException: Method 'RunTargetAsync' in type 'Cake.MyGet.Module.MyGetEngine' from assembly 'Cake.MyGet.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Cake.MyGet.Module.MyGetModule.Register(ICakeContainerRegistrar registrar)
   at Cake.Composition.ModuleLoader.LoadModules(IContainer container, CakeOptions options)
   at Cake.Program.Main()
```

The problem with module exists in Cake `0.29.0` only. The module is working fine with Cake `0.28.1` or older.

**Comment by flcdrg** [comment]
I think that's because in 0.29, they changed the interface ICakeEngine (see https://github.com/cake-build/cake/issues/2094)

**Comment by agc93** [comment]
@SheGe : As @flcdrg correctly pointed out, that was a change introduced in a later version of Cake than the module was built for. If you upgrade to Cake 0.30.0 and the module to [0.3.1](https://www.nuget.org/packages/Cake.BuildSystems.Module/0.3.1) you should not get this error anymore.

**Comment by SheGe** [comment]
@agc93 thanks, after updating to Cake 0.30.0 and module to 0.3.1 everything is working as expected.
